language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require symfony/security-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/finder:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/class-loader:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/yaml:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/browser-kit:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/expression-language:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/event-dispatcher:${SYMFONY_VERSION} --no-update
    - php composer.phar update --no-interaction

phpunit: php vendor/bin/phpunit

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover ./build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
